import vtk
import time
from mcpi.minecraft import Minecraft
import mcpi.block as block
import time
'''
from MXMqtt import MXMqtt
MQTTHOST = "mqtt.16302.com"
MQTTPORT = 1883
mqtt = MXMqtt(MQTTHOST,MQTTPORT)
def pick():
    mqtt.PUB("EIS1","0")
    mqtt.PUB("EIS2","0")
    mqtt.PUB("EIS3","0")
    mqtt.PUB("EIS4","0")
    mqtt.PUB("EIS5","0")
def put():
    mqtt.PUB("EIS1","1")
    mqtt.PUB("EIS2","1")
    mqtt.PUB("EIS3","1")
    mqtt.PUB("EIS4","1")
    mqtt.PUB("EIS5","1")
'''    
    
mc=Minecraft.create("47.100.46.95",4783)
   #Read STL
reader1 = vtk.vtkSTLReader()
reader1.SetFileName("1.stl")
reader2 = vtk.vtkSTLReader()
reader2.SetFileName("2.stl")
reader3 = vtk.vtkSTLReader()
reader3.SetFileName("3.stl")
reader4 = vtk.vtkSTLReader()
reader4.SetFileName("4.stl")
reader5 = vtk.vtkSTLReader()
reader5.SetFileName("dizuo.stl")
reader6 = vtk.vtkSTLReader()
reader6.SetFileName("jixiebi1.stl")
reader7 = vtk.vtkSTLReader()
reader7.SetFileName("jixiebi2.stl")
reader12 = vtk.vtkSTLReader()
reader12.SetFileName("guanjie.stl")
reader8 = vtk.vtkSTLReader()
reader8.SetFileName("jiazi1.stl")
reader9 = vtk.vtkSTLReader()
reader9.SetFileName("jiazibi1.stl")
reader10 = vtk.vtkSTLReader()
reader10.SetFileName("jiazibi2.stl")
reader11 = vtk.vtkSTLReader()
reader11.SetFileName("wuti.stl")
reader13 = vtk.vtkSTLReader()
reader13.SetFileName("xuanzhuan.stl")
 #Create a mapper and actor
mapper1 = vtk.vtkPolyDataMapper()
mapper1.SetInputConnection(reader1.GetOutputPort())
mapper2 = vtk.vtkPolyDataMapper()
mapper2.SetInputConnection(reader2.GetOutputPort())
mapper3 = vtk.vtkPolyDataMapper()
mapper3.SetInputConnection(reader3.GetOutputPort())
mapper4 = vtk.vtkPolyDataMapper()
mapper4.SetInputConnection(reader4.GetOutputPort())
mapper5 = vtk.vtkPolyDataMapper()
mapper5.SetInputConnection(reader5.GetOutputPort())
mapper6 = vtk.vtkPolyDataMapper()
mapper6.SetInputConnection(reader6.GetOutputPort())
mapper7 = vtk.vtkPolyDataMapper()
mapper7.SetInputConnection(reader7.GetOutputPort())
mapper8 = vtk.vtkPolyDataMapper()
mapper8.SetInputConnection(reader8.GetOutputPort())
mapper9 = vtk.vtkPolyDataMapper()
mapper9.SetInputConnection(reader9.GetOutputPort())
mapper10= vtk.vtkPolyDataMapper()
mapper10.SetInputConnection(reader10.GetOutputPort())
mapper11= vtk.vtkPolyDataMapper()
mapper11.SetInputConnection(reader11.GetOutputPort())
mapper12= vtk.vtkPolyDataMapper()
mapper12.SetInputConnection(reader12.GetOutputPort())
mapper13= vtk.vtkPolyDataMapper()
mapper13.SetInputConnection(reader13.GetOutputPort())

actor1 = vtk.vtkActor()
actor1.SetMapper(mapper1)
actor2 = vtk.vtkActor()
actor2.SetMapper(mapper2)
actor3 = vtk.vtkActor()
actor3.SetMapper(mapper3)
actor4 = vtk.vtkActor()
actor4.SetMapper(mapper4)
actor5 = vtk.vtkActor()
actor5.SetMapper(mapper5)
actor6 = vtk.vtkActor()
actor6.SetMapper(mapper6)
actor7 = vtk.vtkActor()
actor7.SetMapper(mapper7)
actor8 = vtk.vtkActor()
actor8.SetMapper(mapper8)
actor9 = vtk.vtkActor()
actor9.SetMapper(mapper9)
actor10 = vtk.vtkActor()
actor10.SetMapper(mapper10)
actor11 = vtk.vtkActor()
actor11.SetMapper(mapper11)
actor12 = vtk.vtkActor()
actor12.SetMapper(mapper12)
actor13 = vtk.vtkActor()
actor13.SetMapper(mapper13)

   # Setup a renderer, render window, and interactor
renderer = vtk.vtkRenderer()
renderWindow = vtk.vtkRenderWindow()
renderWindow.AddRenderer(renderer);
renderWindow.SetSize(1600,800)
renderWindowInteractor = vtk.vtkRenderWindowInteractor()
renderWindowInteractor.SetRenderWindow(renderWindow)

   #Add the actor to the scene
renderer.AddActor(actor1)
renderer.AddActor(actor2)
renderer.AddActor(actor3)
renderer.AddActor(actor4)
renderer.AddActor(actor5)
renderer.AddActor(actor6)
renderer.AddActor(actor7)
renderer.AddActor(actor8)
renderer.AddActor(actor9)
renderer.AddActor(actor10)
renderer.AddActor(actor11)                           
renderer.AddActor(actor12)
renderer.AddActor(actor13)

renderer.SetBackground(0,0,0.8) # RGB 0~1

actor1.SetOrigin(actor13.GetCenter())
actor2.SetOrigin(actor13.GetCenter())
actor3.SetOrigin(actor13.GetCenter())
actor4.SetOrigin(actor13.GetCenter())
actor5.SetOrigin(actor13.GetCenter())
actor6.SetOrigin(actor13.GetCenter())
actor7.SetOrigin(actor13.GetCenter())
actor8.SetOrigin(actor13.GetCenter())
actor9.SetOrigin(actor13.GetCenter())
actor10.SetOrigin(actor13.GetCenter())
actor11.SetOrigin(actor13.GetCenter())
actor12.SetOrigin(actor13.GetCenter())
actor13.SetOrigin(actor13.GetCenter())


actor1.RotateWXYZ(-90,1,0,0)
actor2.RotateWXYZ(-90,1,0,0)
actor3.RotateWXYZ(-90,1,0,0)
actor4.RotateWXYZ(-90,1,0,0)
actor5.RotateWXYZ(-90,1,0,0)
actor6.RotateWXYZ(-90,1,0,0)
actor7.RotateWXYZ(-90,1,0,0)
actor8.RotateWXYZ(-90,1,0,0)
actor9.RotateWXYZ(-90,1,0,0)
actor10.RotateWXYZ(-90,1,0,0)
actor12.RotateWXYZ(-90,1,0,0)
actor13.RotateWXYZ(-90,1,0,0)

#set position
actor11.SetPosition(194,-25,5)
#foward 
for j in range(10):
    actor1.AddPosition(15.5,0,0)
    actor2.AddPosition(15.5,0,0)
    actor3.AddPosition(15.5,0,0)
    actor4.AddPosition(15.5,0,0)

    actor5.AddPosition(15.5,0,0)
    actor6.AddPosition(15.5,0,0)
    actor7.AddPosition(15.5,0,0)
    actor8.AddPosition(15.5,0,0)

    actor9.AddPosition(15.5,0,0)
    actor10.AddPosition(15.5,0,0)
    actor12.AddPosition(15.5,0,0)
    actor13.AddPosition(15.5,0,0)
    time.sleep(0.5)
    renderWindow.Render()
#put down    
for i in range(2):
    actor6.RotateY(10)
    actor7.RotateY(10)
    actor8.RotateY(10)
    actor9.RotateY(10)
    actor10.RotateY(10)
    actor12.RotateY(10)
    time.sleep(0.5)
    renderWindow.Render()
#put()
#pick up
for i in range(2):
    actor6.RotateY(-10)
    actor7.RotateY(-10)
    actor8.RotateY(-10)
    actor9.RotateY(-10)
    actor10.RotateY(-10)
    actor11.AddPosition(1.8,5.2,0)
    actor12.RotateY(-10)
    time.sleep(0.5)
    renderWindow.Render()
#foward second time
#pick()
for j in range(10):
    actor1.AddPosition(9,0,0)
    actor2.AddPosition(9,0,0)
    actor3.AddPosition(9,0,0)
    actor4.AddPosition(9,0,0)
    actor5.AddPosition(9,0,0)
    actor6.AddPosition(9,0,0)
    actor7.AddPosition(9,0,0)
    actor8.AddPosition(9,0,0)
    actor9.AddPosition(9,0,0)
    actor10.AddPosition(9,0,0)
    #actor10.AddPosition(9,0,0)
    actor11.AddPosition(9,0,0)
    actor12.AddPosition(9,0,0)
    actor13.AddPosition(9,0,0)
    time.sleep(0.5)
    renderWindow.Render()
#put down
for i in range(2):
    actor6.RotateY(10)
    actor7.RotateY(10)
    actor8.RotateY(10)
    actor9.RotateY(10)
    actor10.RotateY(10)
    actor11.AddPosition(-1.8,-5.2,0)
    actor12.RotateY(10)    
    time.sleep(0.5)
    renderWindow.Render()
#put()    
mc.setBlock(56,0,88,146)
#pick up
for i in range(2):
    actor6.RotateY(-10)
    actor7.RotateY(-10)
    actor8.RotateY(-10)
    actor9.RotateY(-10)
    actor10.RotateY(-10)
    actor12.RotateY(-10)
    time.sleep(0.5)
    renderWindow.Render()
#Turn around
for l in range(9):
    actor6.RotateZ(-20)
    actor7.RotateZ(-20)
    actor8.RotateZ(-20)
    actor9.RotateZ(-20)
    actor10.RotateZ(-20)
    actor12.RotateZ(-20)
    time.sleep(0.5)
    renderWindow.Render()
#back
for o in range(10):
    actor1.AddPosition(-24.5,0,0)
    actor2.AddPosition(-24.5,0,0)
    actor3.AddPosition(-24.5,0,0)
    actor4.AddPosition(-24.5,0,0)
    actor5.AddPosition(-24.5,0,0)
    actor6.AddPosition(-24.5,0,0)
    actor7.AddPosition(-24.5,0,0)
    actor8.AddPosition(-24.5,0,0)
    actor9.AddPosition(-24.5,0,0)
    actor10.AddPosition(-24.5,0,0)
    actor12.AddPosition(-24.5,0,0)
    actor13.AddPosition(-24.5,0,0)
    time.sleep(0.5)
    renderWindow.Render()   


mc.setBlock(56,0,88,0)
for i in range(9):
   mc.setBlock(57+i,0,88,146)
   time.sleep(0.8)
   mc.setBlock(57+i,0,88,66)
for i in range(4):
   mc.setBlock(56+9,0,88-i,146)
   time.sleep(0.8)
   if i<4:
       mc.setBlock(56+9,0,88-i,66)

mc.setBlock(65,0,84,146)      
    
#renderWindow.Render()

